{
    "name": "Restaurant Booking",
    "version": "18.0.0.0.1",
    "author": "github.com/hungdannt",
    "category": "Website",
    "depends": ["base", "website", "pos_restaurant"],
    "data": [
        "security/ir.model.access.csv",
        "data/sequence.xml",
        "views/restaurant_booking_views.xml",
        "views/portal_templates.xml",
        "views/restaurant_table_views.xml",
        "views/restaurant_time_slot_views.xml",
        "views/menu.xml",
    ],
    "assets": {
        "web.assets_frontend": [
            "restaurant_booking/static/src/scss/booking.scss",
            "restaurant_booking/static/src/js/booking.js",
            "restaurant_booking/static/src/table_booking_template.xml",
            "restaurant_booking/static/src/scss/admin_floor_layout.scss",
            "restaurant_booking/static/src/js/admin_floor_layout.js",
            "restaurant_booking/static/src/admin_floor_layout.xml",
        ],
        "point_of_sale._assets_pos": [
            "restaurant_booking/static/src/app/store/pos_order.js",
            "restaurant_booking/static/src/models/restaurant_booking.js",
            "restaurant_booking/static/src/app/order_summary/order_summary.js",
            "restaurant_booking/static/src/app/booking_list/booking_list.js",
            "restaurant_booking/static/src/app/booking_list/booking_list.xml",
            "restaurant_booking/static/src/app/booking_list/booking_list.scss",          
        ],
    },
    "installable": True,
    "application": True,
}
